--- INIZIO FILE SQL ---

-- DDL dump generated from metadata (representative, not including PL/pgSQL function bodies) -- Project: tnxdohjldclgbyadgdnt -- Schemas: auth, public, storage, realtime, vault -- Generated: automated reconstruction

-- 1) Extensions (install where available) CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; CREATE EXTENSION IF NOT EXISTS "pgcrypto"; CREATE EXTENSION IF NOT EXISTS "pg_stat_statements"; CREATE EXTENSION IF NOT EXISTS "postgis"; CREATE EXTENSION IF NOT EXISTS "postgis_topology"; CREATE EXTENSION IF NOT EXISTS "postgis_sfcgal"; CREATE EXTENSION IF NOT EXISTS "postgis_raster"; CREATE EXTENSION IF NOT EXISTS "pg_trgm"; CREATE EXTENSION IF NOT EXISTS "pgjwt"; -- Note: many other extensions exist in the source (citext, pgroonga, vector, etc.). -- If you need them installed explicitly, add CREATE EXTENSION lines for each.

-- 2) Schemas CREATE SCHEMA IF NOT EXISTS auth; CREATE SCHEMA IF NOT EXISTS public; CREATE SCHEMA IF NOT EXISTS storage; CREATE SCHEMA IF NOT EXISTS realtime; CREATE SCHEMA IF NOT EXISTS vault;

-- 3) Tables: auth schema (representative, includes primary keys and common defaults)

CREATE TABLE IF NOT EXISTS auth.users ( instance_id uuid, id uuid PRIMARY KEY, aud character varying, role character varying, email character varying, encrypted_password character varying, email_confirmed_at timestamptz, invited_at timestamptz, confirmation_token character varying, confirmation_sent_at timestamptz, recovery_token character varying, recovery_sent_at timestamptz, email_change_token_new character varying, email_change character varying, email_change_sent_at timestamptz, last_sign_in_at timestamptz, raw_app_meta_data jsonb, raw_user_meta_data jsonb, is_super_admin boolean, created_at timestamptz, updated_at timestamptz, phone text DEFAULT NULL::character varying, phone_confirmed_at timestamptz, phone_change text DEFAULT ''::character varying, phone_change_token character varying DEFAULT ''::character varying, phone_change_sent_at timestamptz, confirmed_at timestamptz GENERATED ALWAYS AS (LEAST(email_confirmed_at, phone_confirmed_at)) STORED, email_change_token_current character varying DEFAULT ''::character varying, email_change_confirm_status smallint DEFAULT 0 CHECK (email_change_confirm_status >= 0 AND email_change_confirm_status <= 2), banned_until timestamptz, reauthentication_token character varying DEFAULT ''::character varying, reauthentication_sent_at timestamptz, is_sso_user boolean DEFAULT false, deleted_at timestamptz, is_anonymous boolean DEFAULT false );

CREATE TABLE IF NOT EXISTS auth.identities ( provider_id text, user_id uuid, identity_data jsonb, provider text, last_sign_in_at timestamptz, created_at timestamptz, updated_at timestamptz, email text GENERATED ALWAYS AS (lower((identity_data ->> 'email'::text))) STORED, id uuid DEFAULT gen_random_uuid() PRIMARY KEY, CONSTRAINT identities_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) );

CREATE TABLE IF NOT EXISTS auth.sessions ( id uuid PRIMARY KEY, user_id uuid, created_at timestamptz, updated_at timestamptz, factor_id uuid, aal auth.aal_level, -- user-defined enum in source DB not_after timestamptz, refreshed_at timestamp, user_agent text, ip inet, tag text, oauth_client_id uuid, refresh_token_hmac_key text, refresh_token_counter bigint, scopes text, CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id), CONSTRAINT sessions_oauth_client_id_fkey FOREIGN KEY (oauth_client_id) REFERENCES auth.oauth_clients(id) );

CREATE TABLE IF NOT EXISTS auth.refresh_tokens ( instance_id uuid, id bigint PRIMARY KEY, token character varying UNIQUE, user_id character varying, revoked boolean, created_at timestamptz, updated_at timestamptz, parent character varying, session_id uuid, CONSTRAINT refresh_tokens_session_id_fkey FOREIGN KEY (session_id) REFERENCES auth.sessions(id) );

-- (Additional auth tables such as oauth_clients, oauth_authorizations, oauth_consents, one_time_tokens, -- mfa_factors, mfa_challenges, flow_state, saml_providers, etc., exist in the source. Recreate similarly if needed.)

-- 4) Tables: public schema (all tables reconstructed; below is full dump of those enumerated)

CREATE TABLE IF NOT EXISTS public.user_profile ( id uuid PRIMARY KEY, username text, tone text DEFAULT 'playful'::text, likes text[], dislikes text[], memory jsonb, updated_at timestamp DEFAULT now(), name text, full_name text, avatar_url text, is_public boolean, language character varying DEFAULT 'it'::character varying, CONSTRAINT user_profile_user_fkey FOREIGN KEY (id) REFERENCES auth.users(id) );

CREATE TABLE IF NOT EXISTS public.user_profile_media ( id uuid DEFAULT gen_random_uuid() PRIMARY KEY, user_id uuid, image_url text, created_at timestamptz DEFAULT now() );

CREATE TABLE IF NOT EXISTS public.messages ( id uuid DEFAULT uuid_generate_v4() PRIMARY KEY, user_id uuid, session_id text, role text CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text])), type text, content text, created_at timestamptz DEFAULT now(), npc_id uuid, CONSTRAINT messages_npc_id_fkey FOREIGN KEY (npc_id) REFERENCES public.npcs(id) );

CREATE TABLE IF NOT EXISTS public.npcs ( id uuid DEFAULT gen_random_uuid() PRIMARY KEY, user_id uuid, name text, avatar_url text, ethnicity text CHECK (ethnicity = ANY (ARRAY['latina'::text, 'asian'::text, 'european'::text, 'african'::text, 'mixed'::text, 'other'::text])), body_type text CHECK (body_type = ANY (ARRAY['slim'::text, 'curvy'::text, 'athletic'::text, 'petite'::text, 'plus_size'::text])), hair_length text CHECK (hair_length = ANY (ARRAY['short'::text, 'medium'::text, 'long'::text])), hair_color text, eye_color text, height_cm integer, age integer, personality_type text CHECK (personality_type = ANY (ARRAY['sweet'::text, 'sexy'::text, 'shy'::text, 'dominant'::text, 'playful'::text, 'romantic'::text, 'mysterious'::text])), tone text DEFAULT 'flirty'::text, characteristics jsonb DEFAULT '{}'::jsonb, is_active boolean DEFAULT true, is_public boolean DEFAULT false, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), voice_preview_url text, gender text DEFAULT 'female'::text, group_behavior_profile jsonb DEFAULT '{"groupRole": "observer", "talkFrequency": 0.25, "interruptStyle": "polite"}'::jsonb, current_mood text DEFAULT 'neutral'::text, last_interaction_at timestamptz DEFAULT now(), xp integer DEFAULT 0, level integer DEFAULT 1, voice_master_url text, voice_engine text, voice_profile jsonb, CONSTRAINT npcs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) );

CREATE TABLE IF NOT EXISTS public.conversations ( id uuid DEFAULT gen_random_uuid() PRIMARY KEY, user_id uuid, npc_id uuid, last_message_at timestamptz DEFAULT now(), last_message_preview text, unread_count integer DEFAULT 0, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), girlfriend_id uuid, CONSTRAINT conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id), CONSTRAINT conversations_npc_id_fkey FOREIGN KEY (npc_id) REFERENCES public.npcs(id) );

CREATE TABLE IF NOT EXISTS public.groups ( id uuid DEFAULT uuid_generate_v4() PRIMARY KEY, name text, user_id uuid, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now() );

CREATE TABLE IF NOT EXISTS public.group_members ( id uuid DEFAULT uuid_generate_v4() PRIMARY KEY, group_id uuid, npc_id uuid, created_at timestamptz DEFAULT now(), member_id uuid, member_type member_type_enum DEFAULT 'ai'::member_type_enum, role role_enum DEFAULT 'member'::role_enum, CONSTRAINT group_members_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id), CONSTRAINT group_members_npc_id_fkey FOREIGN KEY (npc_id) REFERENCES public.npcs(id) );

CREATE TABLE IF NOT EXISTS public.group_messages ( id uuid DEFAULT uuid_generate_v4() PRIMARY KEY, group_id uuid, sender_id uuid, type text CHECK (type = ANY (ARRAY['text'::text, 'image'::text, 'video'::text, 'audio'::text])), content text, created_at timestamptz DEFAULT now(), CONSTRAINT group_messages_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id) );

CREATE TABLE IF NOT EXISTS public.webhook_logs ( id uuid DEFAULT uuid_generate_v4() PRIMARY KEY, event_type text, payload jsonb, received_at timestamptz DEFAULT now() );

CREATE TABLE IF NOT EXISTS public.chat_memory ( chat_id uuid PRIMARY KEY, summary text, updated_at timestamptz DEFAULT now() );

CREATE TABLE IF NOT EXISTS public.group_memory ( group_id uuid PRIMARY KEY, summary text, dynamics jsonb DEFAULT '{}'::jsonb, updated_at timestamptz DEFAULT now(), shared_history text[] DEFAULT ARRAY[]::text[], inside_jokes text[] DEFAULT ARRAY[]::text[], conflicts text[] DEFAULT ARRAY[]::text[], alliances text[] DEFAULT ARRAY[]::text[], group_mood text DEFAULT 'neutral'::text, created_at timestamptz DEFAULT now(), CONSTRAINT group_memory_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id) );

CREATE TABLE IF NOT EXISTS public.ai_contacts ( id character varying PRIMARY KEY, owner_id character varying, name character varying, avatar text, personality text, style text, tone character varying, age integer, gender character varying, is_public boolean DEFAULT false, description text, rating numeric DEFAULT 0.00, usage_count integer DEFAULT 0, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now() );

CREATE TABLE IF NOT EXISTS public.group_invites ( id uuid DEFAULT gen_random_uuid() PRIMARY KEY, group_id uuid, invited_id uuid, invited_type text CHECK (invited_type = ANY (ARRAY['user'::text, 'ai'::text])), invited_by uuid, status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text])), message text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now() );

CREATE TABLE IF NOT EXISTS public.user_memory ( user_id uuid PRIMARY KEY, preferences jsonb DEFAULT '{}'::jsonb, personality_traits jsonb DEFAULT '{}'::jsonb, life_events text[] DEFAULT ARRAY[]::text[], interests text[] DEFAULT ARRAY[]::text[], emotional_state text DEFAULT 'neutral'::text, conversation_style text DEFAULT 'casual'::text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), CONSTRAINT user_memory_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) );

CREATE TABLE IF NOT EXISTS public.ai_user_memory ( id uuid DEFAULT gen_random_uuid() PRIMARY KEY, ai_id uuid, user_id uuid, relationship_level integer DEFAULT 0 CHECK (relationship_level >= 0 AND relationship_level <= 100), trust_level integer DEFAULT 50 CHECK (trust_level >= 0 AND trust_level <= 100), affection_level integer DEFAULT 50 CHECK (affection_level >= 0 AND affection_level <= 100), shared_experiences text[] DEFAULT ARRAY[]::text[], inside_jokes text[] DEFAULT ARRAY[]::text[], topics_discussed text[] DEFAULT ARRAY[]::text[], user_preferences_learned jsonb DEFAULT '{}'::jsonb, last_interaction timestamptz, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), CONSTRAINT ai_user_memory_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id), CONSTRAINT ai_user_memory_ai_id_fkey FOREIGN KEY (ai_id) REFERENCES public.npcs(id) );

CREATE TABLE IF NOT EXISTS public.ai_relations ( id uuid DEFAULT gen_random_uuid() PRIMARY KEY, ai_id_1 uuid, ai_id_2 uuid, group_id uuid, relationship_type text DEFAULT 'neutral'::text, affinity_level integer DEFAULT 50 CHECK (affinity_level >= 0 AND affinity_level <= 100), tension_level integer DEFAULT 0 CHECK (tension_level >= 0 AND tension_level <= 100), shared_moments text[] DEFAULT ARRAY[]::text[], created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), CONSTRAINT ai_relations_ai_id_2_fkey FOREIGN KEY (ai_id_2) REFERENCES public.npcs(id), CONSTRAINT ai_relations_ai_id_1_fkey FOREIGN KEY (ai_id_1) REFERENCES public.npcs(id), CONSTRAINT ai_relations_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id) );

CREATE TABLE IF NOT EXISTS public.significant_events ( id uuid DEFAULT gen_random_uuid() PRIMARY KEY, ai_id uuid, user_id uuid, group_id uuid, event_type text, description text, emotional_impact text DEFAULT 'medium'::text, created_at timestamptz DEFAULT now(), CONSTRAINT significant_events_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id), CONSTRAINT significant_events_ai_id_fkey FOREIGN KEY (ai_id) REFERENCES public.npcs(id), CONSTRAINT significant_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) );

CREATE TABLE IF NOT EXISTS public.ai_personality_evolution ( id uuid DEFAULT gen_random_uuid() PRIMARY KEY, ai_id uuid, user_id uuid, extroversion integer DEFAULT 50 CHECK (extroversion >= 0 AND extroversion <= 100), humor integer DEFAULT 50 CHECK (humor >= 0 AND humor <= 100), empathy integer DEFAULT 50 CHECK (empathy >= 0 AND empathy <= 100), assertiveness integer DEFAULT 50 CHECK (assertiveness >= 0 AND assertiveness <= 100), playfulness integer DEFAULT 50 CHECK (playfulness >= 0 AND playfulness <= 100), curiosity integer DEFAULT 50 CHECK (curiosity >= 0 AND curiosity <= 100), jealousy integer DEFAULT 30 CHECK (jealousy >= 0 AND jealousy <= 100), loyalty integer DEFAULT 70 CHECK (loyalty >= 0 AND loyalty <= 100), created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), CONSTRAINT ai_personality_evolution_ai_id_fkey FOREIGN KEY (ai_id) REFERENCES public.npcs(id), CONSTRAINT ai_personality_evolution_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) );

CREATE TABLE IF NOT EXISTS public.invites ( id uuid DEFAULT uuid_generate_v4() PRIMARY KEY, group_id uuid, sender_id uuid, receiver_id uuid, receiver_type text CHECK (receiver_type = ANY (ARRAY['user'::text, 'npc'::text])), status text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text, 'cancelled'::text])), context text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), CONSTRAINT invites_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id), CONSTRAINT invites_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id) );

CREATE TABLE IF NOT EXISTS public.npc_posts ( id uuid DEFAULT gen_random_uuid() PRIMARY KEY, npc_id uuid, caption text, media_url text, media_type character varying DEFAULT 'image'::character varying, created_at timestamptz DEFAULT now(), CONSTRAINT npc_posts_npc_id_fkey FOREIGN KEY (npc_id) REFERENCES public.npcs(id) );

CREATE TABLE IF NOT EXISTS public.npc_ratings ( id uuid DEFAULT gen_random_uuid() PRIMARY KEY, npc_id uuid, user_id uuid, rating integer CHECK (rating >= 1 AND rating <= 5), created_at timestamptz DEFAULT now(), CONSTRAINT npc_ratings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profile(id), CONSTRAINT npc_ratings_npc_id_fkey FOREIGN KEY (npc_id) REFERENCES public.npcs(id) );

CREATE TABLE IF NOT EXISTS public.post_likes ( id uuid DEFAULT gen_random_uuid() PRIMARY KEY, post_id uuid, user_id uuid, created_at timestamptz DEFAULT now(), CONSTRAINT post_likes_post_fkey FOREIGN KEY (post_id) REFERENCES public.npc_posts(id), CONSTRAINT post_likes_user_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) );

CREATE TABLE IF NOT EXISTS public.post_comments ( id uuid DEFAULT gen_random_uuid() PRIMARY KEY, post_id uuid, user_id uuid, comment text, created_at timestamptz DEFAULT now(), CONSTRAINT post_comments_post_fkey FOREIGN KEY (post_id) REFERENCES public.npc_posts(id), CONSTRAINT post_comments_user_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) );

CREATE TABLE IF NOT EXISTS public.npc_profiles ( id uuid DEFAULT gen_random_uuid() PRIMARY KEY, owner_id uuid, name text, data jsonb, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), CONSTRAINT npc_profiles_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) );

CREATE TABLE IF NOT EXISTS public.user_credits ( user_id uuid PRIMARY KEY, credits integer DEFAULT 0, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now() );

CREATE TABLE IF NOT EXISTS public.payments ( id uuid DEFAULT gen_random_uuid() PRIMARY KEY, user_id uuid, stripe_session_id text, credits integer, amount character varying, status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'failed'::text])), created_at timestamptz DEFAULT now(), CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) );

CREATE TABLE IF NOT EXISTS public.webhook_logs ( id uuid DEFAULT gen_random_uuid() PRIMARY KEY, event_type text, payload jsonb, received_at timestamptz DEFAULT now() );

-- 5) Tables: storage schema (representative)

CREATE TABLE IF NOT EXISTS storage.buckets ( id text PRIMARY KEY, name text, owner uuid, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), public boolean DEFAULT false, avif_autodetection boolean DEFAULT false, file_size_limit bigint, allowed_mime_types text[], owner_id text, type storage.buckettype DEFAULT 'STANDARD'::storage.buckettype );

CREATE TABLE IF NOT EXISTS storage.objects ( id uuid DEFAULT gen_random_uuid() PRIMARY KEY, bucket_id text, name text, owner uuid, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), last_accessed_at timestamptz DEFAULT now(), metadata jsonb, path_tokens text[] DEFAULT string_to_array(name, '/'::text), version text, owner_id text, user_metadata jsonb, level integer, CONSTRAINT objects_bucketId_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id) );

CREATE TABLE IF NOT EXISTS storage.prefixes ( bucket_id text, name text, level integer DEFAULT storage.get_level(name), created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), PRIMARY KEY (bucket_id, name, level), CONSTRAINT prefixes_bucketId_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id) );

CREATE TABLE IF NOT EXISTS storage.s3_multipart_uploads ( id text PRIMARY KEY, in_progress_size bigint DEFAULT 0, upload_signature text, bucket_id text, key text, version text, owner_id text, created_at timestamptz DEFAULT now(), user_metadata jsonb, CONSTRAINT s3_multipart_uploads_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id) );

CREATE TABLE IF NOT EXISTS storage.s3_multipart_uploads_parts ( id uuid DEFAULT gen_random_uuid() PRIMARY KEY, upload_id text, size bigint DEFAULT 0, part_number integer, bucket_id text, key text, etag text, owner_id text, version text, created_at timestamptz DEFAULT now(), CONSTRAINT s3_multipart_uploads_parts_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES storage.s3_multipart_uploads(id), CONSTRAINT s3_multipart_uploads_parts_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id) );

CREATE TABLE IF NOT EXISTS storage.vector_indexes ( id text DEFAULT gen_random_uuid() PRIMARY KEY, name text, bucket_id text, data_type text, dimension integer, distance_metric text, metadata_configuration jsonb, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), CONSTRAINT vector_indexes_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets_vectors(id) );

-- 6) Tables: realtime schema (representative)

CREATE TABLE IF NOT EXISTS realtime.messages ( topic text, extension text, payload jsonb, event text, private boolean DEFAULT false, updated_at timestamp DEFAULT now(), inserted_at timestamp DEFAULT now(), id uuid DEFAULT gen_random_uuid(), PRIMARY KEY (inserted_at, id) );

CREATE TABLE IF NOT EXISTS realtime.subscription ( id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, subscription_id uuid, entity regclass, filters realtime.user_defined_filter[] DEFAULT '{}'::realtime.user_defined_filter[], claims jsonb, claims_role regrole GENERATED ALWAYS AS (realtime.to_regrole((claims ->> 'role'::text))) STORED, created_at timestamptz DEFAULT timezone('utc', now()) );

-- 7) View: public.users (recreated previously)

DROP VIEW IF EXISTS public.users; CREATE VIEW public.users AS SELECT u.id, u.email, u.raw_user_meta_data, u.raw_app_meta_data, u.phone, u.created_at, u.created_at AS auth_created_at, u.updated_at, u.updated_at AS auth_updated_at, u.last_sign_in_at, u.confirmed_at, up.username, up.name AS full_name, NULL::text AS avatar_url, up.is_public, up.language, up.memory, up.updated_at AS profile_updated_at FROM auth.users u LEFT JOIN public.user_profile up ON up.id = u.id;

-- 8) Comments about missing items -- - Functions (CREATE FUNCTION bodies), triggers, and PL/pgSQL routines were not exhaustively dumped. If you want them included, -- I can extract them by querying pg_proc/pg_trigger and reconstruct the CREATE FUNCTION / CREATE TRIGGER statements. -- - User-defined types and enums used (e.g., member_type_enum, role_enum, storage.buckettype, auth.aal_level, etc.) -- are referred to by name; if you need the exact CREATE TYPE / CREATE TYPE AS ENUM statements, I can extract and add them. -- - Some indexes beyond primary keys are not enumerated here. If you want CREATE INDEX statements, I can extract them.

-- END OF DDL DUMP

--- FINE FILE SQL ---