#!/bin/bash

# Script per setup AI Brain Engine Database
# Esegui questo script dopo aver copiato il contenuto di ddl.sql

echo "🧠 AI BRAIN ENGINE - Database Setup"
echo "===================================="
echo ""
echo "📋 ISTRUZIONI:"
echo ""
echo "1. Apri Supabase Dashboard"
echo "2. Vai su 'SQL Editor'"
echo "3. Crea una nuova query"
echo "4. Copia TUTTO il contenuto di supabase/ddl.sql"
echo "5. Incolla nella query"
echo "6. Clicca 'Run'"
echo ""
echo "✅ Tabelle che verranno create:"
echo "   - user_memory"
echo "   - ai_user_memory"
echo "   - group_memory"
echo "   - ai_relations"
echo "   - significant_events"
echo "   - ai_personality_evolution"
echo ""
echo "📊 Indici e trigger verranno creati automaticamente"
echo ""
echo "⚠️  IMPORTANTE:"
echo "   Se le tabelle esistono già, lo script le salterà (IF NOT EXISTS)"
echo ""
echo "🔐 RLS (Row Level Security) verrà abilitato"
echo "   Modifica le policy secondo le tue esigenze"
echo ""
echo "Premi INVIO quando hai completato l'operazione su Supabase..."
read

echo ""
echo "✅ Setup completato!"
echo ""
echo "🚀 Prossimi step:"
echo "   1. Riavvia il backend: pm2 restart all"
echo "   2. Testa una chat (1-to-1 o gruppo)"
echo "   3. Controlla i log: pm2 logs ws"
echo "   4. Verifica l'apprendimento nel database"
echo ""
echo "📚 Leggi backend/ai/README.md per dettagli"
echo ""
